modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "worldguard"
version = "${version}"
displayName = "World Guard"
authors = "Corgi Taco"
description = '''
Mod that prevents your world from loading if its generator settings changed between now and the last time you loaded your world.
'''
#logoFile = ""

[[dependencies.worldguard]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.worldguard]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "worldguard.mixins.json"
